version: "3.9"
services:
  mysql:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    networks:
      - iris-project-app-network
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: iris-project-app
      TZ: Asia/Shanghai
    command: --default-time-zone='+8:00' --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
  redis:
    container_name: redis7
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    networks:
      - iris-project-app-network
    privileged: true
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - redis-volume:/data
    command: redis-server --requirepass 123 --appendonly yes
  elasticsearch:
    container_name: es8
    image: elasticsearch:8.6.1
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - iris-project-app-network
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    networks:
      - iris-project-app-network
    volumes:
      - mongo-volume:/data/db
  iris-project-app:
    # 使用dockerfile编译 有问题 
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: iris-project-app # 先生成镜像在运行吧
    container_name: iris-project-app
    ports:
      - "8080:8080"
    volumes:
      - iris-project-app-volume:/root/goapp
    networks:
      - iris-project-app-network
    tty: true
    links:
      - redis:redis
      - mysql:mysql
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - mongo
networks:
  iris-project-app-network:
    driver: bridge
volumes:
  iris-project-app-volume:
  mysql-volume:
  redis-volume:
  elastic-volume:
  mongo-volume:
