version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    networks:
      - iris-project-app-network
    privileged: true
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: iris-project-app
      TZ: Asia/Shanghai
    command: --default-time-zone='+8:00' --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
  redis:
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    networks:
      - iris-project-app-network
    privileged: true
    environment:
      - "TZ=Asia/Shanghai"
    container_name: redis
    volumes:
      - redis-volume:/data
    command: redis-server --requirepass 123 --appendonly yes
  iris-project-app:
    # 使用dockerfile编译 有问题 
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: iris-project-app # 先生成镜像在运行吧
    container_name: iris-project-app
    ports:
      - "8080:8080"
    volumes:
      - iris-project-app-volume:/root/goapp
    networks:
      - iris-project-app-network
    tty: true
    links:
      - redis:redis
      - mysql:mysql
    depends_on:
      - mysql
      - redis
networks:
  iris-project-app-network:
    driver: bridge
volumes:
  iris-project-app-volume:
  mysql-volume:
  redis-volume:
