# 支付配置
debug: true
alipay:
  appid: 1234 #应用ID
  publickey: ffffff # 公钥
  privatekey: dfdsfsdf #应用私钥，支持PKCS1和PKCS8
  isprod: true #是否是正式环境
weixinpay:
  mchid: 1608446549 #商户ID 或者服务商模式的 sp_mchid
  serialno: 5776DF2039B2179130D0D8337811F5B029888749 #商户证书的证书序列号
  apiv3key: e10adc3949ba59abbe56e057f20f883e #apiV3Key，商户平台获取
  apiclientcertfile: "config/weixinpay/apiclient_cert.pem" #公钥 apiclient_cert.pem
  apiclientkeyfile: "config/weixinpay/apiclient_key.pem" #私钥 apiclient_key.pem
  newcertfile: "config/weixinpay/new_cert.pem" # 通过微信支付SDK client.GetPlatformCerts() 获取微信平台公钥 并保存到此文件里面
