// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "heyongliang",
            "url": "http://xxx.com",
            "email": "356126067@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/adminapi/adminuser": {
            "post": {
                "description": "创建或更新管理员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "创建或更新管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validate.CreateUpdateAdminUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/adminapi/adminuser/info/{id}": {
            "get": {
                "description": "管理员详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "管理员详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/adminapi/adminuser/list": {
            "get": {
                "description": "管理员列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "管理员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/adminapi/adminuser/{id}": {
            "get": {
                "description": "禁用或启用管理员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "禁用或启用管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除管理员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "删除管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/adminapi/config/list": {
            "get": {
                "description": "配置列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "配置列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "状态",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/adminapi/file/mutiple/upload": {
            "post": {
                "description": "多文件上传",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "多文件上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "uploadfiles",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/adminapi/file/upload": {
            "post": {
                "description": "单文件上传",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "单文件上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "uploadfile",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.Code": {
            "type": "integer",
            "enum": [
                200,
                500,
                403,
                404,
                405,
                406,
                407,
                999,
                1000,
                1001,
                1002,
                1003,
                1004,
                1005,
                1006,
                2000,
                2001,
                2002,
                2003,
                5000
            ],
            "x-enum-comments": {
                "CodeCustom": "自定义错误",
                "CodeNotAllowed": "没有权限"
            },
            "x-enum-varnames": [
                "CodeSucceed",
                "CodeFailed",
                "CodeForbidden",
                "CodeNotFound",
                "CodeRequestParamError",
                "CodeDataHasRelation",
                "CodeDisabled",
                "CodeCustom",
                "CodeUserLoginSucceed",
                "CodeUserRegisterSucceed",
                "CodeUserRegisterFailed",
                "CodeUserNotFound",
                "CodeUserPasswordError",
                "CodeUserForbidden",
                "CodeVerifycodeSucceed",
                "CodeTokenExpired",
                "CodeRefreshTokenExpired",
                "CodeRefreshTokenInvalidated",
                "CodeUserHasBeenLogin",
                "CodeNotAllowed"
            ]
        },
        "app.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/app.Code"
                },
                "data": {},
                "msg": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "global.LocalTime": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "model.Ability": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "model.AdminUser": {
            "type": "object",
            "properties": {
                "ability": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Ability"
                    }
                },
                "created_at": {
                    "$ref": "#/definitions/global.LocalTime"
                },
                "id": {
                    "description": "gorm.Model",
                    "type": "integer"
                },
                "menus": {
                    "description": "所有菜单和接口",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Menu"
                    }
                },
                "phone": {
                    "type": "string"
                },
                "realname": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Role"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "super_admin": {
                    "description": "是否超级管理员",
                    "type": "boolean"
                },
                "unique_auth_keys": {
                    "description": "所有鉴权key",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "$ref": "#/definitions/global.LocalTime"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.Menu": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "前端鉴权key",
                    "type": "string"
                },
                "api_path": {
                    "description": "接口路径",
                    "type": "string"
                },
                "checked": {
                    "description": "是否选中，角色接口中用",
                    "type": "boolean"
                },
                "created_at": {
                    "$ref": "#/definitions/global.LocalTime"
                },
                "expand": {
                    "type": "boolean"
                },
                "header": {
                    "type": "string"
                },
                "html": {
                    "description": "用来输出层级 |----",
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "description": "gorm.Model",
                    "type": "integer"
                },
                "is_header": {
                    "type": "integer"
                },
                "menu_path": {
                    "description": "前端菜单路径",
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "p_id": {
                    "type": "integer"
                },
                "selected": {
                    "type": "boolean"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "description": "1显示 -1隐藏",
                    "type": "integer"
                },
                "subject": {
                    "description": "前端鉴权key",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "unique_auth_key": {
                    "description": "前端鉴权key",
                    "type": "string"
                }
            }
        },
        "model.MenuTree": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "前端鉴权key",
                    "type": "string"
                },
                "api_path": {
                    "description": "接口路径",
                    "type": "string"
                },
                "checked": {
                    "description": "是否选中，角色接口中用",
                    "type": "boolean"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MenuTree"
                    }
                },
                "created_at": {
                    "$ref": "#/definitions/global.LocalTime"
                },
                "expand": {
                    "type": "boolean"
                },
                "header": {
                    "type": "string"
                },
                "html": {
                    "description": "用来输出层级 |----",
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "description": "gorm.Model",
                    "type": "integer"
                },
                "is_header": {
                    "type": "integer"
                },
                "menu_path": {
                    "description": "前端菜单路径",
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "p_id": {
                    "type": "integer"
                },
                "selected": {
                    "type": "boolean"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "description": "1显示 -1隐藏",
                    "type": "integer"
                },
                "subject": {
                    "description": "前端鉴权key",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "unique_auth_key": {
                    "description": "前端鉴权key",
                    "type": "string"
                }
            }
        },
        "model.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/global.LocalTime"
                },
                "id": {
                    "description": "gorm.Model",
                    "type": "integer"
                },
                "jump_page": {
                    "description": "登录后跳转页面",
                    "type": "string"
                },
                "menu_ids": {
                    "description": "菜单IDS",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "menu_names": {
                    "description": "菜单名，用 逗号 分隔",
                    "type": "string"
                },
                "menus_tree": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MenuTree"
                    }
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "validate.CreateUpdateAdminUserRequest": {
            "type": "object",
            "required": [
                "phone",
                "realname",
                "role_ids",
                "username"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                },
                "phone": {
                    "type": "string"
                },
                "realname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "项目接口文档",
	Description:      "windows编译：go build -ldflags \"-s -w -H=windowsgui\" -o=iris-project-daemon.exe",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
