basePath: /
definitions:
  app.Code:
    enum:
    - 200
    - 500
    - 403
    - 404
    - 405
    - 406
    - 407
    - 999
    - 1000
    - 1001
    - 1002
    - 1003
    - 1004
    - 1005
    - 1006
    - 2000
    - 2001
    - 2002
    - 2003
    - 5000
    type: integer
    x-enum-comments:
      CodeCustom: 自定义错误
      CodeNotAllowed: 没有权限
    x-enum-varnames:
    - CodeSucceed
    - CodeFailed
    - CodeForbidden
    - CodeNotFound
    - CodeRequestParamError
    - CodeDataHasRelation
    - CodeDisabled
    - CodeCustom
    - CodeUserLoginSucceed
    - CodeUserRegisterSucceed
    - CodeUserRegisterFailed
    - CodeUserNotFound
    - CodeUserPasswordError
    - CodeUserForbidden
    - CodeVerifycodeSucceed
    - CodeTokenExpired
    - CodeRefreshTokenExpired
    - CodeRefreshTokenInvalidated
    - CodeUserHasBeenLogin
    - CodeNotAllowed
  app.Response:
    properties:
      code:
        $ref: '#/definitions/app.Code'
      data: {}
      msg: {}
      success:
        type: boolean
    type: object
  global.LocalTime:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Ability:
    properties:
      action:
        type: string
      subject:
        type: string
    type: object
  model.AdminUser:
    properties:
      ability:
        items:
          $ref: '#/definitions/model.Ability'
        type: array
      created_at:
        $ref: '#/definitions/global.LocalTime'
      id:
        description: gorm.Model
        type: integer
      menus:
        description: 所有菜单和接口
        items:
          $ref: '#/definitions/model.Menu'
        type: array
      phone:
        type: string
      realname:
        type: string
      roles:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      status:
        type: integer
      super_admin:
        description: 是否超级管理员
        type: boolean
      unique_auth_keys:
        description: 所有鉴权key
        items:
          type: string
        type: array
      updated_at:
        $ref: '#/definitions/global.LocalTime'
      username:
        type: string
    type: object
  model.File:
    properties:
      category_id:
        type: integer
      created_at:
        $ref: '#/definitions/global.LocalTime'
      file_mime:
        type: string
      filename:
        type: string
      full_path:
        type: string
      id:
        type: integer
      is_favor:
        enum:
        - 1
        - -1
        type: integer
      name:
        type: string
      path:
        type: string
      size:
        type: integer
      storage:
        type: string
      type:
        type: string
      upload_by:
        type: string
      upload_by_id:
        type: integer
    required:
    - filename
    - name
    - path
    type: object
  model.FileCategory:
    properties:
      created_at:
        $ref: '#/definitions/global.LocalTime'
      html:
        description: 用来输出层级 |----
        type: string
      p_id:
        type: integer
      selected:
        type: boolean
      title:
        description: json:"name"
        type: string
      value:
        description: json:"id"
        type: integer
    required:
    - title
    type: object
  model.FileCategoryTree:
    properties:
      children:
        items:
          $ref: '#/definitions/model.FileCategoryTree'
        type: array
      created_at:
        $ref: '#/definitions/global.LocalTime'
      html:
        description: 用来输出层级 |----
        type: string
      p_id:
        type: integer
      selected:
        type: boolean
      title:
        description: json:"name"
        type: string
      value:
        description: json:"id"
        type: integer
    required:
    - title
    type: object
  model.Menu:
    properties:
      action:
        description: 前端鉴权key
        type: string
      api_path:
        description: 接口路径
        type: string
      checked:
        description: 是否选中，角色接口中用
        type: boolean
      created_at:
        $ref: '#/definitions/global.LocalTime'
      expand:
        type: boolean
      header:
        type: string
      html:
        description: 用来输出层级 |----
        type: string
      icon:
        type: string
      id:
        description: gorm.Model
        type: integer
      is_header:
        type: integer
      menu_path:
        description: 前端菜单路径
        type: string
      method:
        type: string
      p_id:
        type: integer
      selected:
        type: boolean
      sort:
        type: integer
      status:
        description: 1显示 -1隐藏
        type: integer
      subject:
        description: 前端鉴权key
        type: string
      title:
        type: string
      type:
        type: string
      unique_auth_key:
        description: 前端鉴权key
        type: string
    type: object
  model.MenuTree:
    properties:
      action:
        description: 前端鉴权key
        type: string
      api_path:
        description: 接口路径
        type: string
      checked:
        description: 是否选中，角色接口中用
        type: boolean
      children:
        items:
          $ref: '#/definitions/model.MenuTree'
        type: array
      created_at:
        $ref: '#/definitions/global.LocalTime'
      expand:
        type: boolean
      header:
        type: string
      html:
        description: 用来输出层级 |----
        type: string
      icon:
        type: string
      id:
        description: gorm.Model
        type: integer
      is_header:
        type: integer
      menu_path:
        description: 前端菜单路径
        type: string
      method:
        type: string
      p_id:
        type: integer
      selected:
        type: boolean
      sort:
        type: integer
      status:
        description: 1显示 -1隐藏
        type: integer
      subject:
        description: 前端鉴权key
        type: string
      title:
        type: string
      type:
        type: string
      unique_auth_key:
        description: 前端鉴权key
        type: string
    type: object
  model.Role:
    properties:
      created_at:
        $ref: '#/definitions/global.LocalTime'
      id:
        description: gorm.Model
        type: integer
      jump_page:
        description: 登录后跳转页面
        type: string
      menu_ids:
        description: 菜单IDS
        items:
          type: integer
        type: array
      menu_names:
        description: 菜单名，用 逗号 分隔
        type: string
      menus_tree:
        items:
          $ref: '#/definitions/model.MenuTree'
        type: array
      name:
        type: string
      status:
        type: integer
      tag:
        type: string
    type: object
  validate.CreateUpdateAdminUserRequest:
    properties:
      id:
        type: integer
      password:
        maxLength: 50
        minLength: 4
        type: string
      phone:
        type: string
      realname:
        maxLength: 50
        minLength: 2
        type: string
      role_ids:
        items:
          type: integer
        type: array
      status:
        type: integer
      username:
        maxLength: 50
        minLength: 2
        type: string
    required:
    - phone
    - realname
    - role_ids
    - username
    type: object
host: localhost:8080
info:
  contact:
    email: 356126067@qq.com
    name: heyongliang
    url: http://xxx.com
  description: windows编译：go build -ldflags "-s -w -H=windowsgui" -o=iris-project-daemon.exe
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 项目接口文档
  version: "1.0"
paths:
  /adminapi/adminuser:
    post:
      consumes:
      - application/json
      description: 创建或更新管理员
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求体
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/validate.CreateUpdateAdminUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 创建或更新管理员
      tags:
      - 管理员
  /adminapi/adminuser/{id}:
    delete:
      consumes:
      - application/json
      description: 删除管理员
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 删除管理员
      tags:
      - 管理员
    get:
      consumes:
      - application/json
      description: 禁用或启用管理员
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 禁用或启用管理员
      tags:
      - 管理员
  /adminapi/adminuser/info/{id}:
    get:
      consumes:
      - application/json
      description: 管理员详情
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 管理员详情
      tags:
      - 管理员
  /adminapi/adminuser/list:
    get:
      consumes:
      - application/json
      description: 管理员列表
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 状态
        in: query
        name: status
        type: integer
      - description: 页码
        in: query
        name: page
        type: string
      - description: 页大小
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 管理员列表
      tags:
      - 管理员
  /adminapi/config/list:
    get:
      consumes:
      - application/json
      description: 配置列表
      parameters:
      - description: 名称
        in: query
        name: name
        type: string
      - description: 状态
        in: query
        name: type
        type: integer
      - description: 页码
        in: query
        name: page
        type: string
      - description: 页大小
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 配置列表
      tags:
      - 配置
  /adminapi/file:
    delete:
      consumes:
      - application/json
      description: 删除文件
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求体，格式：{ids:[1,2]}
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 删除文件
      tags:
      - 文件
  /adminapi/file/category:
    put:
      consumes:
      - application/json
      description: 更改文件分类
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求体，格式：{ids:[1,2],name:新名称}
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更改文件分类
      tags:
      - 文件
  /adminapi/file/favor:
    put:
      consumes:
      - application/json
      description: 收藏或取消收藏文件
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求体，格式：{file_id:1}
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 收藏或取消收藏文件
      tags:
      - 文件
  /adminapi/file/list:
    get:
      consumes:
      - application/json
      description: 文件列表
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类ID
        in: query
        name: category_id
        type: string
      - description: 类型
        in: query
        name: type
        type: string
      - description: 名称
        in: query
        name: name
        type: string
      - description: 是否收藏
        in: query
        name: is_favor
        type: integer
      - description: 页码
        in: query
        name: page
        type: string
      - description: 页大小
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 文件列表
      tags:
      - 文件
  /adminapi/file/mutiple/upload:
    post:
      consumes:
      - multipart/form-data
      description: 多文件上传
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件
        in: formData
        name: uploadfiles
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 多文件上传
      tags:
      - 文件
  /adminapi/file/name:
    put:
      consumes:
      - application/json
      description: 修改文件名
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求体，格式：{file_id:1,name:新名称}
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 修改文件名
      tags:
      - 文件
  /adminapi/file/upload:
    post:
      consumes:
      - multipart/form-data
      description: 单文件上传
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件
        in: formData
        name: uploadfile
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 单文件上传
      tags:
      - 文件
  /adminapi/filecategory:
    post:
      consumes:
      - application/json
      description: 创建或更新文件分类
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求体
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/model.FileCategory'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 创建或更新文件分类
      tags:
      - 文件
  /adminapi/filecategory/{id}:
    delete:
      consumes:
      - application/json
      description: 删除文件分类
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 删除文件分类
      tags:
      - 文件
  /adminapi/filecategory/select:
    get:
      consumes:
      - application/json
      description: 文件分类选择项
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 文件分类选择项
      tags:
      - 文件
  /adminapi/filecategory/tree:
    get:
      consumes:
      - application/json
      description: 文件分类树
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: 文件分类树
      tags:
      - 文件
swagger: "2.0"
